"""users table: email_notifications column

Revision ID: 773ac4a8db8a
Revises: ec1b8caf6683
Create Date: 2019-01-31 18:25:23.201757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773ac4a8db8a'
down_revision = 'ec1b8caf6683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_notifications', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_notifications')
    # ### end Alembic commands ###
